
namespace GGD_Hack.GameData
{
    enum RoleId
    {       
    None = 0,
    Goose = 1,
    Duck = 2,
    Dodo = 3,
    Bounty = 4,
    Mechanic = 5,
    Technician = 6,
    Medium = 7,
    Vigilante = 8,
    Cannibal = 9,
    Morphling = 10,
    Sheriff = 11,
    Silencer = 12,
    Canadian = 13,
    LoverDuck = 14,
    LoverGoose = 15,
    Vulture = 16,
    Professional = 17,
    Spy = 18,
    Mimic = 19,
    Detective = 20,
    Pigeon = 21,
    Birdwatcher = 22,
    Assassin = 23,
    Falcon = 24,
    Hitman = 25,
    Bodyguard = 26,
    Snitch = 27,
    Politician = 28,
    Locksmith = 29,
    Mortician = 30,
    Celebrity = 31,
    Party = 32,
    Demolitionist = 33,
    DuelingDodo = 34,
    GHGoose = 35,
    GHDuck = 36,
    GHBounty = 37,
    HNSGoose = 38,
    HNSDuck = 39,
    HNSBounty = 40,
    DNDDuck = 41,
    DNDFalcon = 42,
    DNDVulture = 43,
    DNDMorphling = 44,
    FPGoose = 45,
    ExploreGoose = 46,
    TTVampire = 47,
    TTPeasant = 48,
    TTThrall = 49,
    Spectator = 50,
    IdentityThief = 51,
    Adventurer = 52,
    Avenger = 53,
    Ninja = 54,
    Undertaker = 55,
    Snoop = 56,
    Esper = 57,
    Invisibility = 58,
    Astral = 59,
    Pelican = 60,
    TTEThrall = 61,
    TTMummy = 62,
    SerialKiller = 63,
    Engineer = 64,
    Warlock = 65,
    StreetUrchin = 66,
    Tracker = 67,
    EsperDuck = 68,
    Stalker = 69
    }
}
